ui: tape

browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
  - name: internet explorer
    version: 9..latest
  - name: opera
    version: latest
